package com.tc.PlantNursery.DTO;

import com.tc.PlantNursery.entity.User;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class RegisteredStaffResponse {
    private User user;
    private String autogeneratedPassword;
}
