package com.tc.PlantNursery.controller;

import com.tc.PlantNursery.Dto.LoginResponseDto;
import com.tc.PlantNursery.Dto.RegisteredStaffResponse;
import com.tc.PlantNursery.entity.Product;
import com.tc.PlantNursery.entity.User;
import com.tc.PlantNursery.repository.UserRepo;
import com.tc.PlantNursery.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;

@RestController
@CrossOrigin
public class UserController {

    @Autowired
    private UserService userService;

    @Autowired
    private UserRepo userRepository;

    @Autowired
    private JavaMailSender javaMailSender;


    @PostMapping("/registerUser")
    public User registerUser(@RequestBody User user){
        return userService.registerUser(user);
    }

    @PostMapping("/login")
    public ResponseEntity<Object> validateLogin(@RequestBody HashMap<String, Object> userDetails) {
        String userName = userDetails.get("username").toString();
        String password = userDetails.get("password").toString();

        User foundUser = userService.validateUserLogin(userName, password);

        if (foundUser == null) {
            return new ResponseEntity<>("Unauthorized access", HttpStatus.UNAUTHORIZED);
        } else {
            LoginResponseDto loginResponseDto = new LoginResponseDto();
            loginResponseDto.setId(foundUser.getId());
            loginResponseDto.setUserName(foundUser.getUserName());
            loginResponseDto.setEmail(foundUser.getEmail());
            loginResponseDto.setRole(foundUser.getRole());

            return new ResponseEntity<>(loginResponseDto, HttpStatus.OK);

        }

    }

    /*-------------------admin controllers----------------------*/
    @GetMapping("/admin/showStaffUsersForAdmin")
    public List<User> showStaffUsersForAdmin(){
        return userService.showStaffUsersForAdmin();
    }

    @DeleteMapping("/admin/deleteStaffById/{id}")
    public String deleteStaffUser(@PathVariable Long id){
        return userService.deleteStaffById(id);
    }

    @PostMapping("/admin/registerStaff")
    public String registerStaffByAdmin(@RequestBody User staff) {
        RegisteredStaffResponse response = userService.registerStaffByAdmin(staff);

        SimpleMailMessage simpleMailMessage = new SimpleMailMessage();

        simpleMailMessage.setTo(staff.getEmail());
        simpleMailMessage.setSubject("Your initial credentials");
        simpleMailMessage.setText("Hello " + staff.getUserName() + ",\n"
                + "Your account has been registered by the admin.\n"
                + "Username: " + staff.getUserName() + "\n"
                + "Password: " + response.getAutogeneratedPassword() + "\n"
                + "Please log in and reset your password.\n"
                + "Thank you for joining!");

        javaMailSender.send(simpleMailMessage);
        return "credentials sent successfully to "+ staff.getEmail();
    }


    /*-------------------Nursery staff controllers----------------------*/
    @PatchMapping("/staff/resetPassword")
    public ResponseEntity<String> resetPassword(@RequestBody User user) {
        if (user == null || user.getId() == null || user.getPassword() == null) {
            return ResponseEntity.badRequest().body("User ID and new password are required.");
        }

        boolean success = userService.resetPassword(user.getId(), user.getPassword());

        if (success) {
            return ResponseEntity.ok("Password reset successfully.");
        } else {
            return ResponseEntity.badRequest().body("Failed to reset password.");
        }
    }

    @PostMapping("/staff/addProduct")
    public Product addProduct(@RequestBody Product product){
        return userService.addProduct(product);
    }

    @PatchMapping("/staff/updateProduct")
    public ResponseEntity<String> updateProduct(@RequestBody Product product){
        if(product == null || product.getId() == null || product.getPrice() == null || product.getStockStatus() == null ){
            return ResponseEntity.badRequest().body("Product,price and status required");
        }
        boolean success = userService.updateProduct(product.getId(), product.getPrice(), product.getStockStatus());

        if (success) {
            return ResponseEntity.ok("Updated the product successfully.");
        } else {
            return ResponseEntity.badRequest().body("Failed to update the product");
        }
    }


}
